### ISSUE TITLE
Type error on build

### ISSUE THREAD

**Issue by dmihal** [Zoltu/deterministic-deployment-proxy#2]
I tried following the setup instructions, but go the following error on `npm run build`:

```
scripts/compile.ts:92:77 - error TS2345: Argument of type 'ArrayBuffer' is not assignable to parameter of type 'BNInput'.
  Type 'ArrayBuffer' is missing the following properties from type 'Buffer': write, toJSON, equals, compare, and 75 more.

92  const signerAddress = arrayFromHexString(keccak256(secp256k1.recoverPubKey(hashedSignedEncodedTransaction, { r: r, s: s}, 0).encode('array').slice(1)).slice(-40))
                                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/Users/dmihal/keystone/burner/deterministic-deployment-proxy/node_modules/ts-node/src/index.ts:240:12)
    at reportTSError (/Users/dmihal/keystone/burner/deterministic-deployment-proxy/node_modules/ts-node/src/index.ts:244:19)
    at getOutput (/Users/dmihal/keystone/burner/deterministic-deployment-proxy/node_modules/ts-node/src/index.ts:360:34)
    at Object.compile (/Users/dmihal/keystone/burner/deterministic-deployment-proxy/node_modules/ts-node/src/index.ts:393:11)
    at Module.m._compile (/Users/dmihal/keystone/burner/deterministic-deployment-proxy/node_modules/ts-node/src/index.ts:439:43)
    at Module._extensions..js (module.js:664:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/dmihal/keystone/burner/deterministic-deployment-proxy/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

**Comment by MicahZoltu** [comment]
Ah, sorry about that.  I had a local change in a type for a dependency while waiting for an upstream change to get merged.  The upstream change eventually got merged and pushed to GitHub but apparently I didn't update to the new version.  Will fix now.

**Comment by MicahZoltu** [comment]
Sorry for the delay in getting it fixed.  Readme instructions should work now.
